server:
  port: 8081
  
spring:
  application:
    name: inventory
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

